spring:
  datasource:
    url: jdbc:mysql://10.0.0.20/lineage
    username: darts
    password: target
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug
