spring:
  datasource:
    url: jdbc:mysql://localhost:33306/lineage
    username: darts
    password: target
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com:
      messio:
        lineage: debug
    org:
      hibernate:
        SQL: info
